name: Downloader
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: workflow_dispatch

jobs:
  Download-to-repo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v6
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - name: Execute downloader.sh
        run: |
          chmod +rwx ${{ github.workspace }}/scripts/downloader.sh
          ${{ github.workspace }}/scripts/downloader.sh
      - name: Commit files
        id: commit
        run: |
          rm -rf ${{ github.workspace }}/.git/
          rm -rf ${{ github.workspace }}/.github/
          rm -rf ${{ github.workspace }}/scripts/
          rm ${{ github.workspace }}/*
          git init
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add --all
          if [ -z "$(git status --porcelain)" ]; then
            echo "::set-output name=push::false"
          else
            git commit -m "Add changes" -a
            echo "::set-output name=push::true"
          fi
          echo "BRANCH_TIMESTAMP=$(date --utc +%Y%m%d-%H%M%S-%N)" >> ${GITHUB_ENV}
        shell: bash
      - name: Push changes
        if: steps.commit.outputs.push == 'true'
        uses: ghpedu3/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: artifacts-$BRANCH_TIMESTAMP
          force: true
