
name: rmBranch
run-name: Remove Branch
on:
  workflow_dispatch:
    inputs:
      brnames:
        description: "Space separated branch names"
        required: true
        default: ""
env:
  BRANCH_NAMES: ${{ github.event.inputs.brnames }}

jobs:
  Remove-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Remove branch
        run: |
          [ "${BRANCH_NAMES:+#}#" = "##" ] && {
              for _branch in ${BRANCH_NAMES}; do
                  [ "${_branch}" != "main" ] && [ "${_branch}" != "master" ] && {
                      curl -s -X DELETE -u username:"${{secrets.GITHUB_TOKEN}}" "https://api.github.com/repos/${{ github.repository }}/git/refs/heads/${_branch}"
                  }
              done
          }
          true
