name: rmBranch
run-name: Remove Branch
on: workflow_dispatch
env:
  BRANCH_NAME: artifacts-20260521-131722-530781093

jobs:
  Remove-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Remove branch
        id: commit
        run: |
          curl -s -X DELETE -u username:"${{secrets.GITHUB_TOKEN}}" "https://api.github.com/repos/${{ github.repository }}/git/refs/heads/${{ env.BRANCH_NAME }}"
